on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --manifest-path ./contests/Cargo.toml -- --check

  deno:
    name: Deno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check formatting
        run: deno fmt --check tools/
      - name: Lint
        run: deno lint tools/

  actions:
    name: GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        uses: reviewdog/action-actionlint@v1
